import { ThemeType } from './theme.types';

export const themes: { [key: string]: ThemeType } = {
  casual: {
    'bs-body-bg': '#ffffff',
    'bs-body-color': '#f8f7f7',
    'bs-toggle-sidebar-btn-hover': '#f2f2f2',
    'bs-new-convo-text-color': '#0D0D0D',
    'bs-new-convo-text-color-hover': 'white',
    'bs-new-convo-border-color': '#0D0D0D',
    'bs-new-convo-border-color-hover': '#0D0D0D',
    'bs-new-convo-bg-color-hover': '#0D0D0D',
    'bs-profile-dropdown-bg': '#ffffff',
    'bs-usr-icon-color': 'darkgray',
    'bs-profile-dropdown-border-bg': 'darkgray',
    'bs-dropdown-row-hover-bg': '#f2f2f2',
    'bs-btn-primary-bg': '#007bff',
    'sidebar-bg': '#f9f9f9',
    'bs-toggle-sidebar-open-bg': '#0D0D0D',
    'bs-toggle-sidebar-close-bg': '#0D0D0D',
    'bs-msg-bg': '#F8F9FA',
    'bs-msg-bar-bg': '#f4f4f4',
    'bs-textarea-color': 'black',
    'bs-default-btn-bg': '#e0dfdf',
    'bs-inactive-btn-bg': '#D7D7D7',
    'bs-active-btn-bg': '#0D0D0D',
    'bs-msg-bubble-text-color': '#0D0D0D',
    'bs-msg-bubble-bg': '#f4f4f4',
    'bs-msg-bubble-loading-bg': '#f4f4f4',
    'bs-table-header-color': '#f4f4f4',
    'bs-table-header-data-color' : '#0D0D0D',
    'bs-table-border-color': '#f4f4f4',
    'bs-table-button-color': '#0D0D0D',
    'bs-table-data-color': '#202124',
    'bs-table-btn-hover-bg': '#f2f2f2',
    'sidebar-text-color': '#0D0D0D',
    'sidebar-text-color-active': '#3A4D39',
    'bs-conversation-item-hover-bg': '#f2f2f2',
    // Typography
    'bs-font-sans-serif': 'system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", "Liberation Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"',
  },
  dark: {
    'bs-body-bg': '#212121',
    'bs-body-color': '#f8f9fa',
    'sidebar-bg': '#18191a',
    'bs-toggle-sidebar-open-bg': '#ffffff',
    'bs-toggle-sidebar-close-bg': '#ffffff',
    'bs-toggle-sidebar-btn-hover': '#4a4a4a',
    'bs-new-convo-text-color': '#fffff',
    'bs-new-convo-text-color-hover': '#18191a',
    'bs-new-convo-border-color': 'white',
    'bs-new-convo-border-color-hover': '#18191a',
    'bs-new-convo-bg-color-hover': 'white',
    'bs-profile-dropdown-bg': '#2F2F2F',
    'bs-usr-icon-color': 'darkgray',
    'bs-profile-dropdown-border-bg': '#4a4a4a',
    'bs-dropdown-row-hover-bg': '#4a4a4a',
    'bs-btn-primary-bg': '#6c757d',
    'bs-btn-primary-color': '#ffffff',
    'bs-link-hover-color': '#789',
    'bs-background-color': '#000000',
    'bs-msg-bg': '#212121',
    'bs-msg-bubble-bg': '#2F2F2F',
    'bs-msg-bubble-text-color': '#ffffff',
    'bs-msg-bubble-loading-bg': '#2F2F2F',
    'bs-msg-bar-bg': '#2F2F2F',
    'bs-textarea-color': '#ffffff',
    'bs-inactive-btn-bg': 'darkgray',
    'bs-active-btn-bg': '#ffffff',
    'bs-table-header-color': '#2F2F2F',
    'bs-table-header-data-color' : '#ffffff',
    'bs-table-border-color': '#4a4a4a',
    'bs-table-button-color': '#ffffff',
    'bs-table-data-color': '#ffffff',
    'bs-table-btn-hover-bg': '#4a4a4a',
    'sidebar-text-color': '#ffffff',
    'sidebar-text-color-active': 'grey',
    'bs-conversation-item-hover-bg': '#4a4a4a',
    // Typography
    'bs-font-sans-serif': 'system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", "Liberation Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"',
  }
};